myName = input("Hey there, what is your name : ")
myAge = input("how Old are you :  ")
print("Gee, that's REALLY OLD")
replit = input("do you like Replit?")
print("OF COURSE YOU DO!")

print("So you are")
print(myName)
print("and are the ripe old age of ")
print(myAge)
print("and clearly think that Replit is ")
print(replit)

print("Getting to know you!")
name = input("What's your name?: ")
favfood = input("What's your favourite food: ")
favmusic = input("What's your favourite music? ")
place = input("Where do you live?:  ")

print("You are")
print(name)
print("You're probably hungry for ")
print(favfood)
print("and you're definitely getting your groove on to ")
print(favmusic)
print("living in the amazing")
print(place)
